---
branding: wzy
sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - users
  - grubcfg
  - bootloader
  - umount
- show:
  - finished
